# Generated by Django 3.2.24 on 2024-02-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20240218_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_image1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_image3',
        ),
    ]
